# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Resistance Dashboard

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Suggestions for content for this dashboard, send to <a href="mailto:contact@resistancedashboard.com">contact@resistancedashboard.com</a>


## Production values
# baseurl: ""
# url: "http://resistancedashboard.com"

## Dev values
baseurl: "/dev"
url: "http://resistance-dashboard.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass

gems:
  - jekyll-autoprefixer
  
exclude:
  - CNAME
  - .gitignore
  - bin
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gems
  - Procfile
  - Rakefile
  - README.md
  - script
  - vendor
  - .ruby-version
  - Guardfile
  - .jekyll-assets-cache
  - .sass-cache
  - .editorconfig
  - .idea
  - .ruby-version
  - .asset-cache
